version: 2
jobs:
  build_35: &DEFAULT
     docker:
       - image: quantumblacklabs/kedro_builder:3.5.2
     steps:
       - checkout
       - run:
          name: Install Java 1.8
          command: |
            sudo apt install openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
       - run: &CONDA_SETUP
          name: Activate conda environment
          command: |
            echo ". /home/circleci/miniconda/etc/profile.d/conda.sh" >> $BASH_ENV
            echo "conda deactivate; conda activate kedro_builder" >> $BASH_ENV
       - run: &PIP_SETUP
          name: Install PIP dependencies
          command: |
            # echo python version for debugging
            echo "Python version: $(python --version 2>&1)"

            # Install pip setuptools
            make install-pip-setuptools

            # Install requirements
            pip install -r requirements.txt -U

            # Install test requirements
            pip install -r test_requirements.txt -U
       - run:
          name: Run pylint and flake8
          command: |
            make lint
       - run:
          name: Run tests
          command: |
            make test
       - run:
          name: Run all end to end tests
          command: |
            make e2e-tests
       - run:
           name: Check docs build on Python 3.6+
           command: |
             if python -c "import sys; sys.exit(sys.version_info[:2] == (3, 5))" ; then
                 make build-docs
             fi
       - run:
          name: Check for legal compliance
          command: |
            make legal
  build_36:
     <<: *DEFAULT
     docker:
       - image: quantumblacklabs/kedro_builder:3.6
  build_37:
     <<: *DEFAULT
     docker:
       - image: quantumblacklabs/kedro_builder:3.7

workflows:
  version: 2
  regular:
    jobs:
      - build_35
      - build_36
      - build_37
